apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bgd-app
  namespace: argocd
spec:
  destination:
    namespace: bdg
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps
    repoURL: https://github.com/nvpidstoob/ArgoCD
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
    
